name: Set up godzil
description: Install godzil and add it to PATH
author: Songmu

runs:
  using: composite
  steps:
    - name: Install godzil
      shell: bash
      run: |
        version="v0.22.1"
        bindir="${RUNNER_TEMP%/}/godzil/bin"

        sh "${GITHUB_ACTION_PATH}/install.sh" \
          -b "${bindir}" "${version}"
        echo "${bindir}" >> "${GITHUB_PATH}"
      env:
        # Authenticate gh attestation verify.
        GH_TOKEN: ${{ github.token }}

branding:
  icon: package
  color: blue
