name: tagpr
on:
  push:
    branches:
    - "main"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: checkout
      uses: actions/checkout@v4
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "steps.tagpr.outputs.tag != ''"
