name: tagpr
on:
  push:
    branches:
    - "main"
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pull-requests: write
  issues: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: setup go
      uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: checkout
      uses: actions/checkout@v4
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "steps.tagpr.outputs.tag != ''"
